# Пет-проект "Платформа продуктовой аналитики и A/B-тестирования"

## Цель проекта

В данном проекте моделируется работа аналитической платформы интернет-магазина.

В ходе проекта:

- генерируются пользователи и их события;
- события сохраняются в PostgreSQL;
- выполняется исследовательский анализ данных;
- рассчитываются продуктовые метрики;
- проводится анализ A/B-теста;
- результаты визуализируются в DataLens.

В данном ноутбуке выполняется аналитическая часть проекта: проверка качества данных, анализ продуктовой воронки и оценка результатов эксперимента.

In [50]:
import pandas as pd
from sqlalchemy import create_engine
import os
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
import scipy.stats as stats
from scipy.stats import chi2_contingency
from IPython.display import Markdown, display
pio.renderers.default = 'notebook_connected'
pio.renderers.default = 'iframe'

In [51]:
engine = create_engine("postgresql+psycopg2://user:password@localhost:5422/db")

## 1. Загрузка данных

In [52]:
query = '''
    SELECT e.event_id,
           e.user_id,
           e.type_event,
           e.time_event,
           e.metadata,
           u.test_group,
           u.date_registration
    FROM raw.events e
    JOIN raw.users u ON u.user_id = e.user_id
'''

In [53]:
df_raw = pd.read_sql(query, engine)

## 2. Первичная проверка данных

In [54]:
df_raw.head()

,event_id,user_id,type_event,time_event,metadata,test_group,date_registration
0,f64e7ed1-8d27-4af3-9864-ea2ca6b51aa2,14788,click,2026-06-29 08:52:57,{},A,2026-06-25 12:20:01
1,850ae411-610b-4fe3-b346-a8c2ac303f22,14399,click,2026-06-29 11:51:28,{},A,2026-06-22 09:52:58
2,bb4a40c9-7c30-4686-98a0-be82b6e34155,13864,click,2026-06-29 11:26:16,{},B,2026-06-28 12:05:19
3,b57fc700-eadc-41cc-9f90-303274b4c89e,13864,view,2026-06-29 18:20:49,{},B,2026-06-28 12:05:19
4,8273b38a-ae89-4204-a070-4632d52f0f20,8375,view,2026-06-29 08:22:35,{},A,2026-05-30 16:14:46

In [55]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 169992 entries, 0 to 169991
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   event_id           169992 non-null  str
 1   user_id            169992 non-null  int64
 2   type_event         169992 non-null  str
 3   time_event         169992 non-null  datetime64[us]
 4   metadata           169992 non-null  object
 5   test_group         169992 non-null  str
 6   date_registration  169992 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), object(1), str(3)
memory usage: 9.1+ MB

In [77]:
df_raw['date'] = df_raw.time_event.dt.date

#### 2.1 Количество пользователей

In [56]:
print("=" * 60)
print("Проверка качества данных")
print("=" * 60)
users_count = df_raw["user_id"].nunique()
print(f"Количество уникальных пользователей: {users_count}")

============================================================
Проверка качества данных
============================================================
Количество уникальных пользователей: 23317

#### 2.2 Распределение пользователей между группами эксперимента

In [57]:
users_by_group = (df_raw.drop_duplicates(subset=['test_group', 'user_id'])['test_group'].value_counts())
print("\nРаспределение пользователей по группам")

for group, count in users_by_group.items():
    print(f"Группа {group}: {count} пользователей")

Распределение пользователей по группам
Группа B: 11798 пользователей
Группа A: 11519 пользователей

#### 2.3 Распределение событий

In [58]:
df_raw.groupby(['type_event'], as_index = False).agg({'user_id':'count'})

    type_event  user_id
0  add_to_cart     6353
1        click    47340
2     purchase     1222
3         view   115077

In [59]:
events = (df_raw["type_event"]
    .value_counts()
    .rename_axis("Событие")
    .reset_index(name="Количество"))
events

       Событие  Количество
0         view      115077
1        click       47340
2  add_to_cart        6353
3     purchase        1222

#### 2.4 Активность пользователей

In [60]:
events_per_user = df_raw.groupby("user_id").size()

print("\nКоличество событий на пользователя")

print(f"Среднее : {events_per_user.mean():.2f}")
print(f"Медиана : {events_per_user.median():.0f}")
print(f"Максимум: {events_per_user.max()}")

Количество событий на пользователя
Среднее : 7.29
Медиана : 7
Максимум: 31

In [63]:
events_by_group_day = (
    df_raw
    .groupby([
        df_raw['time_event'].dt.date,
        'test_group'
    ])
    .size()
    .reset_index(name='events')
)

fig = px.line(
    events_by_group_day,
    x='time_event',
    y='events',
    color='test_group',
    markers=True,
    title='Количество событий по дням в разрезе тестовых групп'
)

fig.update_layout(
    xaxis_title='Дата',
    yaxis_title='Количество событий'
)

fig.show()

In [78]:
events_by_group_day = (
    df_raw.groupby([df_raw["time_event"].dt.date,"test_group"]).size().reset_index(name="events")
    .pivot(index="time_event",columns="test_group",values="events").reset_index())

events_by_group_day.columns.name = None
events_by_group_day

    time_event     A     B
0   2026-06-29  5421  5809
1   2026-06-30  5533  5934
2   2026-07-01  5785  6036
3   2026-07-02  5820  6238
4   2026-07-03  5230  5409
5   2026-07-04  6802  6793
6   2026-07-05  6938  7248
7   2026-07-06  5440  5790
8   2026-07-07  5567  5900
9   2026-07-08  5793  6028
10  2026-07-09  5888  6170
11  2026-07-10  5224  5415
12  2026-07-11  6555  7040
13  2026-07-12  6850  7336


Распределение количества событий по дням в контрольной и тестовой группах остается сопоставимым на протяжении всего периода эксперимента.

Явных расхождений между группами не наблюдается: обе группы демонстрируют схожую динамику изменения числа событий, что свидетельствует о равномерном распределении трафика между вариантами A и B.

Выраженных аномалий, способных существенно повлиять на результаты дальнейшего анализа, не обнаружено.

In [72]:
display(Markdown(f"""
### Промежуточный вывод

На данном этапе была выполнена первичная проверка данных.

- В эксперименте участвуют **{users_count:,}** уникальных пользователей.
- Среднее количество событий на пользователя — **{events_per_user.mean():.2f}**.
- Медианное количество событий — **{events_per_user.median():.0f}**.
- Максимальное количество событий — **{events_per_user.max()}**.
"""))

### Промежуточный вывод

На данном этапе была выполнена первичная проверка данных.

- В эксперименте участвуют **23,317** уникальных пользователей.
- Среднее количество событий на пользователя — **7.29**.
- Медианное количество событий — **7**.
- Максимальное количество событий — **31**.

## 3. Анализ продуктовой воронки

На данном этапе определим количество уникальных пользователей,
дошедших до каждого этапа продуктовой воронки.

Это позволит оценить эффективность каждого шага
и станет основой для дальнейшего анализа A/B-теста.

In [24]:
stage_order = ['view','click', 'add_to_cart', 'purchase']

In [25]:
funnel_by_users = df_raw.groupby(['test_group', 'type_event'], as_index=False).agg(size=('user_id', 'nunique'))
funnel_by_users['type_event'] = pd.Categorical(funnel_by_users['type_event'], categories=stage_order, ordered=True)
funnel_by_users = funnel_by_users.sort_values(by='type_event')
funnel_by_users

  test_group   type_event   size
3          A         view  10366
7          B         view  10459
1          A        click   8580
5          B        click   8697
0          A  add_to_cart   2299
4          B  add_to_cart   2901
2          A     purchase    538
6          B     purchase    669

In [26]:
group_A = funnel_by_users[funnel_by_users['test_group']=='A']
group_B = funnel_by_users[funnel_by_users['test_group']=='B']

In [27]:
group_A

  test_group   type_event   size
3          A         view  10366
1          A        click   8580
0          A  add_to_cart   2299
2          A     purchase    538

In [28]:
group_B

  test_group   type_event   size
7          B         view  10459
5          B        click   8697
4          B  add_to_cart   2901
6          B     purchase    669

In [29]:
fig = go.Figure()
fig.add_trace(go.Funnel(
    name = 'Группа A',
    y = group_A['type_event'],
    x = group_A['size'],
    textinfo = "value+percent initial"
))

fig.add_trace(go.Funnel(
    name = 'Группа B',
    y = group_B['type_event'],
    x = group_B['size'],
    textinfo = "value+percent initial"
))

fig.update_layout(
    title_text="Конверсия воронки по тестовым группам",
    funnelmode="group"
)

fig.show()

### Вывод

На графике представлена воронка пользовательских действий отдельно для контрольной (A) и тестовой (B) групп.

На первых двух этапах (*просмотр товара* и *клик по карточке*) различия между группами практически отсутствуют, что свидетельствует о сопоставимом объеме пользовательского трафика.

Наиболее заметное отличие наблюдается на этапе **добавления товара в корзину**: пользователи тестовой группы совершают это действие чаще, чем пользователи контрольной группы.

Аналогичная тенденция сохраняется и на этапе покупки — в тестовой группе количество завершённых покупок также выше.

Визуальный анализ позволяет предположить, что изменения интерфейса положительно повлияли на конверсию. Однако окончательный вывод можно сделать только после проверки статистической значимости различий.
"""

In [30]:
funnel = (df_raw.groupby(['test_group','type_event'])['user_id'].nunique().unstack())
funnel

type_event  add_to_cart  click  purchase   view
test_group
A                  2299   8580       538  10366
B                  2901   8697       669  10459

In [31]:
funnel = funnel[
    ["view", "click", "add_to_cart", "purchase"]
]

funnel

type_event   view  click  add_to_cart  purchase
test_group
A           10366   8580         2299       538
B           10459   8697         2901       669

In [32]:
conversion = pd.DataFrame(index=funnel.index)

conversion["View → Click"] = funnel["click"] / funnel["view"]
conversion["Click → Cart"] = (funnel["add_to_cart"] / funnel["click"])
conversion["Cart → Purchase"] = (funnel["purchase"] / funnel["add_to_cart"])
conversion["View → Purchase"] = (funnel["purchase"] /funnel["view"])
conversion = (conversion.mul(100).round(2))

conversion

            View → Click  Click → Cart  Cart → Purchase  View → Purchase
test_group
A                  82.77         26.79            23.40             5.19
B                  83.15         33.36            23.06             6.40

In [33]:
display(Markdown(f"""
## Вывод

На данном этапе была построена продуктовая воронка отдельно для тестовых групп **A** и **B**.

Полученные результаты показывают, что пользователи группы **B** проходят все этапы воронки успешнее пользователей группы **A**.

Основные различия:

- Конверсия **View → Click** выросла с **{conversion.loc['A','View → Click']:.2f}%** до **{conversion.loc['B','View → Click']:.2f}%**.
- Конверсия **Click → Add to Cart** выросла с **{conversion.loc['A','Click → Cart']:.2f}%** до **{conversion.loc['B','Click → Cart']:.2f}%**.
- Конверсия **Add to Cart → Purchase** также немного выше в группе **B**.
- Общая конверсия **View → Purchase** составляет **{conversion.loc['A','View → Purchase']:.2f}%** в группе **A** против **{conversion.loc['B','View → Purchase']:.2f}%** в группе **B**.

По визуальному сравнению можно предположить, что изменение, протестированное в группе **B**, положительно влияет на поведение пользователей. Однако на данном этапе это является лишь наблюдением. Чтобы сделать вывод о наличии статистически значимых различий между группами, необходимо провести статистический анализ.
"""))

## Вывод

На данном этапе была построена продуктовая воронка отдельно для тестовых групп **A** и **B**.

Полученные результаты показывают, что пользователи группы **B** проходят все этапы воронки успешнее пользователей группы **A**.

Основные различия:

- Конверсия **View → Click** выросла с **82.77%** до **83.15%**.
- Конверсия **Click → Add to Cart** выросла с **26.79%** до **33.36%**.
- Конверсия **Add to Cart → Purchase** также немного выше в группе **B**.
- Общая конверсия **View → Purchase** составляет **5.19%** в группе **A** против **6.40%** в группе **B**.

По визуальному сравнению можно предположить, что изменение, протестированное в группе **B**, положительно влияет на поведение пользователей. Однако на данном этапе это является лишь наблюдением. Чтобы сделать вывод о наличии статистически значимых различий между группами, необходимо провести статистический анализ.

## 4. Проверка статистических гипотез

До данного момента сравнение групп основывалось только на визуальном анализе и рассчитанных конверсиях.

Однако различия между группами могут возникать случайно. Поэтому необходимо проверить, являются ли наблюдаемые различия статистически значимыми.

Целью эксперимента являлось увеличение количества пользователей, добавляющих товары в корзину. Поэтому основной метрикой для оценки результатов теста выбрана конверсия Click → Add to Cart. Остальные показатели продуктовой воронки рассматриваются как вторичные метрики и используются для оценки общего влияния изменений на поведение пользователей.

H0:
Конверсия Click → Add to Cart одинакова.

H1:
Конверсия Click → Add to Cart различается.

#### 4.1 Подготовка данных для статистического анализа

In [34]:
target_events = ["click", "add_to_cart"]

df_ab = (
    df_raw[df_raw["type_event"].isin(target_events)]
    .pivot_table(
        index=["user_id", "test_group"],
        columns="type_event",
        aggfunc="size",
        fill_value=0).reset_index())

df_ab["clicked"] = (df_ab["click"] > 0).astype(int)
df_ab["added_to_cart"] = (df_ab["add_to_cart"] > 0).astype(int)

df_ab = df_ab[["user_id", "test_group", "clicked", "added_to_cart"]]
df_ab.head()

type_event  user_id test_group  clicked  added_to_cart
0                 2          A        1              1
1                 3          B        1              1
2                 6          B        1              1
3                 8          A        1              0
4                 9          A        1              0

Для проверки статистической гипотезы данные были агрегированы на уровне пользователей. Для каждого участника эксперимента сформированы бинарные признаки, отражающие факт совершения ключевых действий. Такой подход позволяет использовать пользователя в качестве единицы наблюдения, что соответствует методологии проведения A/B-тестов.

In [35]:
print(f"Количество пользователей: {len(df_ab):,}")

display(
    df_ab.groupby("test_group")[["clicked", "added_to_cart"]]
    .sum()
)

Количество пользователей: 17,277

type_event  clicked  added_to_cart
test_group
A              8580           2299
B              8697           2901

### 4.2 Формирование таблицы сопряженности

In [36]:
contingency_table = pd.crosstab(
    df_ab["test_group"],
    df_ab["added_to_cart"]
)

contingency_table.columns = [
    "Не добавил в корзину",
    "Добавил в корзину"
]

contingency_table

            Не добавил в корзину  Добавил в корзину
test_group
A                           6281               2299
B                           5796               2901

Для проверки статистической гипотезы была сформирована таблица сопряженности, отражающая количество пользователей, совершивших и не совершивших целевое действие в каждой тестовой группе.

Именно эта таблица является входными данными для критерия χ² Пирсона, который позволяет определить, являются ли различия между группами статистически значимыми.

### 4.3 Проверка статистической значимости (χ²-тест Пирсона)

После формирования таблицы сопряженности можно проверить,
являются ли различия между тестовыми группами случайными
или они статистически значимы.

Для проверки используется критерий χ² Пирсона,
который применяется для сравнения категориальных данных
(например, совершил пользователь целевое действие или нет).

Уровень значимости принимаем равным α = 0.05.

In [37]:
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

In [38]:
alpha = 0.05

if p_value < alpha:
    conclusion = (
        "Нулевая гипотеза отвергается. "
        "Различия между тестовыми группами статистически значимы."
    )
else:
    conclusion = (
        "Различия между группами статистически значимы. Полученный эффект с высокой вероятностью не является следствием случайности."
    )

print(conclusion)

Нулевая гипотеза отвергается. Различия между тестовыми группами статистически значимы.

In [39]:
display(Markdown(f"""
## Интерпретация результатов

Полученное значение **p-value = {p_value:.6f}**.

Уровень значимости был выбран **α = 0.05**.

Поскольку

**p-value {'<' if p_value < 0.05 else '>'} 0.05**,

можно сделать следующий вывод:

> **{conclusion}**
"""))

## Интерпретация результатов

Полученное значение **p-value = 0.000000**.

Уровень значимости был выбран **α = 0.05**.

Поскольку

**p-value < 0.05**,

можно сделать следующий вывод:

> **Нулевая гипотеза отвергается. Различия между тестовыми группами статистически значимы.**

#### 4.4 Ожидаемое распределение

Если бы изменение дизайна никак не влияло на вероятность добавления товара в корзину, то ожидаемое количество пользователей в каждой категории выглядело бы следующим образом.

In [40]:
expected_df = pd.DataFrame(
    expected,
    index=contingency_table.index,
    columns=contingency_table.columns
)

expected_df.round(2)

            Не добавил в корзину  Добавил в корзину
test_group
A                        5997.61            2582.39
B                        6079.39            2617.61

In [41]:
conv_A = contingency_table.loc["A", "Добавил в корзину"] / contingency_table.loc["A"].sum()

conv_B = contingency_table.loc["B", "Добавил в корзину"] / contingency_table.loc["B"].sum()

print(f"Конверсия группы A: {conv_A:.2%}")
print(f"Конверсия группы B: {conv_B:.2%}")

Конверсия группы A: 26.79%
Конверсия группы B: 33.36%

In [42]:
absolute_lift = conv_B - conv_A

print(f"Абсолютный прирост: {absolute_lift:.2%}")

Абсолютный прирост: 6.56%

In [43]:
relative_lift = (conv_B - conv_A) / conv_A

print(f"Относительный прирост: {relative_lift:.2%}")

Относительный прирост: 24.49%

In [44]:
display(Markdown(f"""
## 4.5 Размер эффекта

После подтверждения статистической значимости необходимо оценить практическую значимость изменений.

Конверсия группы **A** составила **{conv_A:.2%}**.

Конверсия группы **B** составила **{conv_B:.2%}**.

Абсолютный прирост конверсии составил **{absolute_lift:.2%}**.

Относительный прирост (**uplift**) составил **{relative_lift:.2%}**.

Полученные результаты показывают, что изменение интерфейса действительно увеличило долю пользователей, добавляющих товар в корзину.
"""))

## 4.5 Размер эффекта

После подтверждения статистической значимости необходимо оценить практическую значимость изменений.

Конверсия группы **A** составила **26.79%**.

Конверсия группы **B** составила **33.36%**.

Абсолютный прирост конверсии составил **6.56%**.

Относительный прирост (**uplift**) составил **24.49%**.

Полученные результаты показывают, что изменение интерфейса действительно увеличило долю пользователей, добавляющих товар в корзину.

## 4.6 Доверительный интервал разницы конверсий

Статистическая значимость показывает, что различия между группами маловероятно возникли случайно.

Однако для принятия продуктового решения важно оценить диапазон возможных значений эффекта.

Для этого построим 95%-й доверительный интервал для разницы конверсий между тестовой и контрольной группами.

In [45]:
n_A = contingency_table.loc["A"].sum()
n_B = contingency_table.loc["B"].sum()

x_A = contingency_table.loc["A", "Добавил в корзину"]
x_B = contingency_table.loc["B", "Добавил в корзину"]

In [46]:
se = np.sqrt(
    conv_A * (1 - conv_A) / n_A +
    conv_B * (1 - conv_B) / n_B
)

In [47]:
z = 1.96

ci_low = absolute_lift - z * se
ci_high = absolute_lift + z * se

print(f"95% доверительный интервал: [{ci_low:.2%}; {ci_high:.2%}]")

95% доверительный интервал: [5.20%; 7.93%]

In [48]:
display(Markdown(f"""
### Интерпретация доверительного интервала

Полученный 95%-й доверительный интервал для разницы конверсий составляет

**от {ci_low:.2%} до {ci_high:.2%}.**

Это означает, что с вероятностью 95% истинный эффект изменения интерфейса находится именно в этом диапазоне.

Поскольку весь доверительный интервал расположен **выше нуля**, можно сделать вывод, что тестовая версия демонстрирует устойчивое улучшение конверсии по сравнению с контрольной группой.

Полученные результаты подтверждают не только статистическую значимость различий, но и их практическую ценность для продукта.
"""))

### Интерпретация доверительного интервала

Полученный 95%-й доверительный интервал для разницы конверсий составляет

**от 5.20% до 7.93%.**

Это означает, что с вероятностью 95% истинный эффект изменения интерфейса находится именно в этом диапазоне.

Поскольку весь доверительный интервал расположен **выше нуля**, можно сделать вывод, что тестовая версия демонстрирует устойчивое улучшение конверсии по сравнению с контрольной группой.

Полученные результаты подтверждают не только статистическую значимость различий, но и их практическую ценность для продукта.

In [49]:
display(Markdown(f"""
# 5. Итоговый вывод

Целью данного исследования было оценить влияние изменений интерфейса страницы товара на поведение пользователей с помощью A/B-теста.

В ходе работы были выполнены следующие этапы анализа:

- проведена загрузка и предварительная проверка данных;
- исследован состав пользователей и распределение событий;
- построена воронка пользовательских действий;
- выполнено сравнение конверсий между контрольной и тестовой группами;
- проверена статистическая гипотеза с использованием критерия χ²;
- рассчитан размер эффекта и построен 95%-й доверительный интервал для разницы конверсий.

По результатам исследования установлено, что:

- конверсия контрольной группы составила **{conv_A:.2%}**;
- конверсия тестовой группы составила **{conv_B:.2%}**;
- абсолютный прирост конверсии составил **{absolute_lift:.2%}**;
- относительный прирост (**uplift**) составил **{relative_lift:.2%}**;
- критерий χ² показал статистически значимые различия между группами (**p-value < 0.05**);
- 95%-й доверительный интервал полностью расположен выше нуля (**от {ci_low:.2%} до {ci_high:.2%}**), что подтверждает устойчивость наблюдаемого эффекта.

Таким образом, полученные результаты свидетельствуют о том, что изменения интерфейса положительно повлияли на конверсию пользователей в добавление товара в корзину. Вероятность того, что наблюдаемый эффект обусловлен случайностью, крайне мала.

При отсутствии негативного влияния на другие продуктовые показатели (например, конверсию в покупку, средний чек, выручку или пользовательский опыт) тестовую версию можно рекомендовать к дальнейшему внедрению.
"""))

# 5. Итоговый вывод

Целью данного исследования было оценить влияние изменений интерфейса страницы товара на поведение пользователей с помощью A/B-теста.

В ходе работы были выполнены следующие этапы анализа:

- проведена загрузка и предварительная проверка данных;
- исследован состав пользователей и распределение событий;
- построена воронка пользовательских действий;
- выполнено сравнение конверсий между контрольной и тестовой группами;
- проверена статистическая гипотеза с использованием критерия χ²;
- рассчитан размер эффекта и построен 95%-й доверительный интервал для разницы конверсий.

По результатам исследования установлено, что:

- конверсия контрольной группы составила **26.79%**;
- конверсия тестовой группы составила **33.36%**;
- абсолютный прирост конверсии составил **6.56%**;
- относительный прирост (**uplift**) составил **24.49%**;
- критерий χ² показал статистически значимые различия между группами (**p-value < 0.05**);
- 95%-й доверительный интервал полностью расположен выше нуля (**от 5.20% до 7.93%**), что подтверждает устойчивость наблюдаемого эффекта.

Таким образом, полученные результаты свидетельствуют о том, что изменения интерфейса положительно повлияли на конверсию пользователей в добавление товара в корзину. Вероятность того, что наблюдаемый эффект обусловлен случайностью, крайне мала.

При отсутствии негативного влияния на другие продуктовые показатели (например, конверсию в покупку, средний чек, выручку или пользовательский опыт) тестовую версию можно рекомендовать к дальнейшему внедрению.

## Ограничения исследования

Следует учитывать, что исследование имеет ряд ограничений:

- анализ выполнен на синтетических данных;
- оценивалась только конверсия пользователей в добавление товара в корзину;
- не анализировалось влияние изменений на средний чек и итоговую выручку;
- не исследовались долгосрочные метрики, такие как удержание пользователей или повторные покупки.

При проведении реального A/B-теста продуктовое решение рекомендуется принимать с учетом совокупности бизнес-метрик.

In [79]:
df_raw.to_csv("df_raw.csv", index=False)